- name: Установка Docker на сервере
  hosts: all  # Указывает на то, что Playbook будет запускаться на всех хостах, указанных в файле инвентаря
  tags: docker
  become: yes  # Повышение привилегий для выполнения задач с правами администратора (аналог sudo)
  tasks:
     - import_tasks: config/docker.yaml

# почему local
#- name: Установка pip (если требуется)
#  hosts: localhost
#  connection: local
#  gather_facts: yes
#  become: yes
#  tasks:
#    - name: Установка pip
#      apt:
#        name: python3-pip
#        state: present
#      when: ansible_distribution == 'Ubuntu'
#
#    - name: Установка Docker SDK для Python
#      pip:
#        name: docker

- name: Установка утилит
  hosts: all
  become: yes
  tasks:
    - import_tasks: config/utils.yaml

- name: Развертывание проекта Taiga
  hosts: all
  become: yes
  tasks:
    - import_tasks: config/taiga.yaml


- name: Развертывание проекта Backend test
  hosts: all
  become: yes
  tasks:
    - import_tasks: config/backend_test.yaml

- name: Reclone taiga to yandex
  hosts: all
  tags: test
  tasks:
    - import_tasks: config/rclone.yaml



#    - name: Debug
#      tags: debug
#      debug:
#        msg: "test {{ ansible_host }}"

# name: "Check port {{ ansible_port }}"